version: '3.1'

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sdl7
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
