version: '3.4'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: sdl
      POSTGRES_USER: kate
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  web:
    build: .
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: "Host=sdl7-db-1;Database=sdl;Username=kate;Password=password"